# Generated by Django 4.1.2 on 2022-10-31 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anschlusstyp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bezeichnung', models.CharField(max_length=50, verbose_name='Bezeichnung')),
                ('slug', models.CharField(max_length=50, verbose_name='Anschlusstyp')),
            ],
            options={
                'verbose_name': 'Anschlusstyp',
                'verbose_name_plural': 'Anschlusstypen',
            },
        ),
        migrations.CreateModel(
            name='Arbeitsspeichertyp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typ', models.CharField(max_length=50, verbose_name='Typ')),
                ('groesse', models.IntegerField(verbose_name='Größe in GB')),
                ('takt', models.CharField(max_length=50, verbose_name='Takt')),
                ('ecc', models.BooleanField(verbose_name='ECC tauglich')),
            ],
            options={
                'verbose_name': 'Arbeitsspeichertyp',
                'verbose_name_plural': 'Arbeitsspeichertypen',
            },
        ),
        migrations.CreateModel(
            name='Computer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zusatzinfo', models.CharField(max_length=50, null=True, verbose_name='Zusatzinfo')),
            ],
            options={
                'verbose_name': 'Computer',
                'verbose_name_plural': 'Computer',
            },
        ),
        migrations.CreateModel(
            name='Einsatzgebiet',
            fields=[
                ('slug', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Abkürzung')),
                ('bezeichnung', models.CharField(max_length=50, verbose_name='Bezeichnung')),
            ],
            options={
                'verbose_name': 'Einsatzgebiet',
                'verbose_name_plural': 'Einsatzgebiete',
            },
        ),
        migrations.CreateModel(
            name='NICTyp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typ', models.CharField(max_length=50, verbose_name='NIC Typ')),
                ('bezeichnung', models.CharField(max_length=50, verbose_name='Bezeichnung')),
            ],
            options={
                'verbose_name': 'NIC Typ',
                'verbose_name_plural': 'NIC Typen',
            },
        ),
        migrations.CreateModel(
            name='Ort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ort', models.CharField(max_length=50, verbose_name='Ort')),
            ],
            options={
                'verbose_name': 'Ort',
                'verbose_name_plural': 'Orte',
            },
        ),
        migrations.CreateModel(
            name='Prozessor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bezeichnung', models.CharField(max_length=50, verbose_name='Bezeichnung')),
                ('takt', models.CharField(max_length=10, verbose_name='Takt')),
                ('anzahl_kerne', models.IntegerField(verbose_name='Anzahl Kerne')),
            ],
            options={
                'verbose_name': 'Prozessor',
                'verbose_name_plural': 'Prozessoren',
            },
        ),
        migrations.CreateModel(
            name='Raum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raum', models.CharField(max_length=50, verbose_name='Raum')),
                ('ort', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='app1.ort', verbose_name='Ort')),
            ],
            options={
                'verbose_name': 'Raum',
                'verbose_name_plural': 'Räume',
            },
        ),
        migrations.CreateModel(
            name='Sorte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Bezeichnung', models.CharField(max_length=50, verbose_name='Bezeichnung')),
            ],
            options={
                'verbose_name': 'Sorte',
                'verbose_name_plural': 'Sorten',
            },
        ),
        migrations.CreateModel(
            name='Speicherart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bezeichnung', models.CharField(max_length=50, verbose_name='Bezeichnung')),
                ('slug', models.CharField(max_length=50, verbose_name='Typ')),
            ],
            options={
                'verbose_name': 'Massenspeicherart',
                'verbose_name_plural': 'Massenspeicherarten',
            },
        ),
        migrations.CreateModel(
            name='Standort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bezeichnung', models.CharField(max_length=50, verbose_name='Behälter')),
                ('raum', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='app1.raum', verbose_name='Raum')),
            ],
            options={
                'verbose_name': 'Standort',
                'verbose_name_plural': 'Standorte',
            },
        ),
        migrations.CreateModel(
            name='NIC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mac', models.CharField(max_length=50, verbose_name='MAC Adresse')),
                ('kommentar', models.CharField(max_length=50, null=True, verbose_name='MAC Adresse')),
                ('typ', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='app1.nictyp', verbose_name='Typ')),
            ],
            options={
                'verbose_name': 'NIC',
                'verbose_name_plural': 'NIC',
            },
        ),
        migrations.CreateModel(
            name='Massenspeichertyp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bezeichnung', models.CharField(max_length=50, verbose_name='Bezeichnung')),
                ('groesse', models.CharField(max_length=50, verbose_name='Größe')),
                ('anschluss', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='app1.anschlusstyp', verbose_name='Anschluss')),
                ('typ', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='app1.speicherart', verbose_name='Speicherart')),
            ],
            options={
                'verbose_name': 'Massenspeichertyp',
                'verbose_name_plural': 'Massenspeichertypen',
            },
        ),
        migrations.CreateModel(
            name='Massenspeicher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('computer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='app1.computer', verbose_name='Anschluss')),
                ('speichertyp', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='app1.massenspeichertyp')),
            ],
            options={
                'verbose_name': 'Massensspeicher',
                'verbose_name_plural': 'Massensspeicher',
            },
        ),
        migrations.CreateModel(
            name='Einsatzmoeglichkeit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('computer', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='app1.computer', verbose_name='Computer')),
                ('einsatzgebiet', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='app1.einsatzgebiet', verbose_name='Einsatzgebiet')),
            ],
            options={
                'verbose_name': 'Einsatzmöglichkeit',
                'verbose_name_plural': 'Einsatzmöglichkeit',
            },
        ),
        migrations.AddField(
            model_name='computer',
            name='prozessor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='app1.prozessor', verbose_name='Prozessor'),
        ),
        migrations.AddField(
            model_name='computer',
            name='standort',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='app1.standort', verbose_name='Standort'),
        ),
        migrations.CreateModel(
            name='Arbeitsspeicher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speichertyp', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='app1.arbeitsspeichertyp')),
            ],
            options={
                'verbose_name': 'Arbeitsspeicher',
                'verbose_name_plural': 'Arbeitsspeicher',
            },
        ),
    ]
