# Generated by Django 4.1.2 on 2022-10-31 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computer',
            name='zusatzinfo',
            field=models.CharField(blank=True, max_length=50, verbose_name='Zusatzinfo'),
        ),
        migrations.AlterField(
            model_name='massenspeicher',
            name='computer',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.RESTRICT, to='app1.computer', verbose_name='Computer'),
        ),
    ]
