# Generated by Django 4.1.2 on 2022-11-02 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_alter_computer_zusatzinfo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hersteller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hersteller', models.CharField(max_length=50, verbose_name='Hersteller')),
            ],
            options={
                'verbose_name': 'Hersteller',
                'verbose_name_plural': 'Hersteller',
            },
        ),
        migrations.AddField(
            model_name='arbeitsspeicher',
            name='computer',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.RESTRICT, to='app1.computer', verbose_name='Computer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='arbeitsspeicher',
            name='seriennummer',
            field=models.CharField(default='', max_length=50, verbose_name='SN'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='computer',
            name='modell',
            field=models.CharField(blank=True, max_length=50, verbose_name='Modell'),
        ),
        migrations.AddField(
            model_name='computer',
            name='product',
            field=models.CharField(blank=True, max_length=50, verbose_name='Produkt'),
        ),
        migrations.AddField(
            model_name='computer',
            name='seriennummer',
            field=models.CharField(blank=True, max_length=50, verbose_name='SN'),
        ),
        migrations.AddField(
            model_name='massenspeicher',
            name='comment',
            field=models.CharField(default='', max_length=50, verbose_name='SN'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='massenspeicher',
            name='seriennummer',
            field=models.CharField(blank=True, max_length=50, verbose_name='SN'),
        ),
        migrations.AlterField(
            model_name='standort',
            name='bezeichnung',
            field=models.CharField(max_length=50, verbose_name='Standort'),
        ),
        migrations.AddField(
            model_name='computer',
            name='hersteller',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.RESTRICT, to='app1.hersteller', verbose_name='Hersteller'),
            preserve_default=False,
        ),
    ]
