# Generated by Django 4.1.2 on 2022-11-02 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_hersteller_arbeitsspeicher_computer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computer',
            name='hersteller',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.RESTRICT, to='app1.hersteller', verbose_name='Hersteller'),
        ),
    ]
