# Generated by Django 4.1.2 on 2022-11-02 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_arbeitsspeicher_hersteller_massenspeicher_hersteller_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='massenspeicher',
            name='hersteller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='app1.hersteller', verbose_name='Hersteller'),
        ),
    ]
