# Generated by Django 4.1.2 on 2022-11-02 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_alter_massenspeicher_hersteller'),
    ]

    operations = [
        migrations.AddField(
            model_name='computer',
            name='pin',
            field=models.CharField(default='000000', max_length=50, verbose_name='PIN'),
        ),
        migrations.AlterField(
            model_name='arbeitsspeicher',
            name='seriennummer',
            field=models.CharField(blank=True, max_length=50, verbose_name='SN'),
        ),
        migrations.AlterField(
            model_name='computer',
            name='hersteller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='app1.hersteller', verbose_name='Hersteller'),
        ),
    ]
