# Generated by Django 4.1.2 on 2022-11-02 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_computer_pin_alter_arbeitsspeicher_seriennummer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prozessor',
            name='anzahl_kerne_logisch',
            field=models.IntegerField(default=0, verbose_name='Anzahl logischer Kerne'),
        ),
    ]
