# Generated by Django 4.1.2 on 2022-11-03 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_prozessor_anzahl_kerne_logisch'),
    ]

    operations = [
        migrations.AddField(
            model_name='nic',
            name='computer',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.RESTRICT, to='app1.computer', verbose_name='Computer'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='nic',
            name='kommentar',
            field=models.CharField(max_length=50, null=True, verbose_name='Kommentar'),
        ),
    ]
