# Generated by Django 4.1.2 on 2022-11-07 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0014_alter_arbeitsspeicher_seriennummer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='massenspeicher',
            name='computer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='app1.computer', verbose_name='Computer'),
        ),
        migrations.AlterField(
            model_name='nic',
            name='computer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='app1.computer', verbose_name='Computer'),
        ),
        migrations.AlterField(
            model_name='nic',
            name='kommentar',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Kommentar'),
            preserve_default=False,
        ),
    ]
