# Generated by Django 4.1.2 on 2022-11-07 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0015_alter_massenspeicher_computer_alter_nic_computer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToolTyp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typ', models.CharField(max_length=50, verbose_name='ToolTyp ')),
                ('kommentar', models.CharField(blank=True, max_length=50, verbose_name='Kommentar')),
            ],
            options={
                'verbose_name': 'Tooltypen',
                'verbose_name_plural': 'Tooltyp',
            },
        ),
        migrations.CreateModel(
            name='Tools',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zusatzinfo', models.CharField(blank=True, max_length=50, verbose_name='Zusatzinfo')),
                ('computer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='app1.computer', verbose_name='Computer')),
                ('standort', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='app1.standort', verbose_name='Standort')),
            ],
            options={
                'verbose_name': 'Tool',
                'verbose_name_plural': 'Tools',
            },
        ),
    ]
