# Generated by Django 4.1.2 on 2022-11-07 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0016_tooltyp_tools'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tools',
            new_name='Tool',
        ),
    ]
