# Generated by Django 4.1.2 on 2022-11-08 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0021_alter_tool_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='bezeichnung',
            field=models.CharField(blank=True, max_length=50, verbose_name='Bezeichnung'),
        ),
        migrations.AlterField(
            model_name='tool',
            name='zusatzinfo',
            field=models.CharField(blank=True, max_length=250, verbose_name='Zusatzinfo'),
        ),
    ]
